#!/usr/bin/env bash
#Configure your Nginx server so
#that /redirect_me is redirecting to another page

apt-get -y update
apt-get -y install nginx
echo "Hello World!" | sed tee /var/www/html/index.html
redir="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$redir/" /etc/nginx/sites-enabled/default
sudo service nginx restart